/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotl

import java.util.Arrays

class App {
    val greeting: String
        get() {
            return "Hello world."
        }

    fun arrJugglery(): Unit {
      var iArr = intArrayOf(4, 19, 23, 57, 79, 93)

      println(iArr.joinToString(prefix="{", postfix="}"))

      val array = arrayOf(intArrayOf(1, 2),
              intArrayOf(3, 4),
              intArrayOf(5, 6, 7))

      println(Arrays.deepToString(array))
    }

}

/*
val animals = listOf("raccoon", "reindeer", "cow", "camel", "giraffe", "goat")

// grouping by first char and collect only max of contains vowels
val compareByVowelCount = compareBy { s: String -> s.count { it in "aeiou" } }

val maxVowels = animals.groupingBy { it.first() }
                    .reduce { _, a, b -> maxOf(a, b, compareByVowelCount) }

println(animals[0].first()) // {r=reindeer, c=camel, g=giraffe}

*/

fun main(args: Array<String>) {
    val iArr = intArrayOf(87, 93, 57, 19, 4, 79, 23)
    // selectionSort(iArr)
    // bubbleSort(iArr)

}
